/******************************************************************************

Copyright (c) 2010, Cormac Flanagan (University of California, Santa Cruz)
                    and Stephen Freund (Williams College) 

All rights reserved.  

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

 * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the following
      disclaimer in the documentation and/or other materials provided
      with the distribution.

 * Neither the names of the University of California, Santa Cruz
      and Williams College nor the names of its contributors may be
      used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 ******************************************************************************/

package rr.barrier;

import rr.event.Event;
import rr.state.ShadowThread;
import acme.util.Util;

/**
 * A barrier event generated by a BarrierMonitor.
 */
public class BarrierEvent<T> extends Event {

	/** The barrier object. */
	protected T barrier;
	
	/** Whether the current thread is entering. */
	protected boolean entering;
	
	/** The number of threads that will block before leaving the barrier. */
	protected int parties;
	
	/** How many threads are currently waiting for the barrier. */
	protected int count;
	
	/**
	 * RoadRunner internal method.
	 */
	public BarrierEvent(ShadowThread td, T barrier, boolean entering) {
		super(td);
		this.barrier = barrier;
		this.entering = entering;
	}

	@Override
	public String toString() {
		return String.format("Barrier(%d,%s,%s)", getThread().getTid(), Util.objectToIdentityString(barrier), entering ? "Enter":"Exit");
	}

	public T getBarrier() {
		return barrier;
	}

	public boolean isEntering() {
		return entering;
	}

	/**
	 * RoadRunner internal method.
	 */
	public void setBarrier(T barrier) {
		this.barrier = barrier;
	}

	/**
	 * RoadRunner internal method.
	 */
	public void setEntering(boolean entering) {
		this.entering = entering;
	}

	public int getParties() {
		return parties;
	}

	/**
	 * RoadRunner internal method.
	 */
	public void setParties(int parties) {
		this.parties = parties;
	}

	public int getCount() {
		return count;
	}

	/**
	 * RoadRunner internal method.
	 */
	public void setCount(int count) {
		this.count = count;
	}

}
